AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

Semicolon:
  Exclude:
    - spec/**/*

Lambda:
  Enabled: false

RegexpLiteral:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Enabled: false

MultilineBlockChain:
  Enabled: false

